import { PaginaLegal } from "@/componentes/PaginaLegal";

export default function TermosUso() {
  return <PaginaLegal titulo="Termos de Uso" subtitulo="Regras para utilização responsável e segura do OnKash Finance.">
    <section><h2>1. Identificação</h2><p>O OnKash Finance é disponibilizado por Pedro Henrique Benvento, Curitiba/PR, contato <a href="mailto:onkashfinance@gmail.com">onkashfinance@gmail.com</a>. Estes Termos formam o acordo entre o responsável pela conta e a plataforma.</p></section>
    <section><h2>2. Objeto</h2><p>A plataforma oferece recursos de organização e controle financeiro pessoal e empresarial, incluindo lançamentos, contas, relatórios, planejamento, importação e análise. O serviço é uma ferramenta de apoio e não presta consultoria contábil, jurídica, tributária ou de investimentos.</p></section>
    <section><h2>3. Cadastro e segurança da conta</h2><p>O usuário deve fornecer informações verdadeiras, manter seus dados atualizados, proteger senha e dispositivo e comunicar suspeitas de acesso indevido. A conta é pessoal; usuários empresariais devem respeitar as permissões concedidas. É proibido compartilhar credenciais ou tentar acessar dados de terceiros.</p></section>
    <section><h2>4. Uso permitido</h2><p>É proibido utilizar o serviço para fraude, lavagem de dinheiro, violação de direitos, distribuição de malware, exploração de vulnerabilidades, automação abusiva ou envio de conteúdo ilícito. O acesso poderá ser limitado para proteger usuários, cumprir lei ou interromper abuso comprovado, com informação adequada quando possível.</p></section>
    <section><h2>5. Dados inseridos</h2><p>O usuário permanece responsável pela legalidade, exatidão e autorização para inserir dados, documentos, clientes, fornecedores e colaboradores. A plataforma trata essas informações apenas para fornecer e proteger o serviço, conforme a Política de Privacidade.</p></section>
    <section><h2>6. Planos e pagamentos</h2><p>A versão atual pode ser utilizada no plano gratuito. Limites exibidos são informativos enquanto a cobrança não estiver ativa. Antes do lançamento de planos pagos serão apresentados preço, periodicidade, renovação, cancelamento e eventuais limites, sem cobrança automática baseada apenas no registro de interesse.</p></section>
    <section><h2>7. Disponibilidade e alterações</h2><p>Buscamos manter o serviço disponível e seguro, mas podem ocorrer manutenções, falhas de fornecedores ou eventos fora do controle razoável. Funcionalidades podem evoluir; mudanças que reduzam direitos ou alterem materialmente a relação serão comunicadas.</p></section>
    <section><h2>8. Responsabilidade</h2><p>O usuário deve conferir informações antes de tomar decisões ou cumprir obrigações. A plataforma não se responsabiliza por dados inseridos incorretamente, decisões tomadas exclusivamente com base em projeções, perda causada por credenciais compartilhadas ou indisponibilidade inevitável de terceiros, sem afastar responsabilidades que não possam ser excluídas pela legislação brasileira.</p></section>
    <section><h2>9. Propriedade intelectual</h2><p>A marca, interface, código, textos e elementos do OnKash pertencem aos respectivos titulares. O uso da plataforma não transfere propriedade intelectual. Os dados financeiros inseridos continuam pertencendo ao usuário ou aos seus legítimos titulares.</p></section>
    <section><h2>10. Encerramento e dados</h2><p>O usuário pode pedir encerramento pelo portal de Privacidade e dados. Antes disso, poderá exportar suas informações. A exclusão observará obrigações legais, prevenção de fraude, direitos de terceiros e preservação de registros empresariais; dados não necessários serão eliminados ou anonimizados.</p></section>
    <section><h2>11. Lei aplicável e conflitos</h2><p>Aplica-se a legislação brasileira, inclusive a LGPD e, quando caracterizada relação de consumo, o Código de Defesa do Consumidor. Estes Termos não restringem acesso à ANPD, órgãos de defesa do consumidor ou ao foro assegurado por lei ao usuário.</p></section>
    <section><h2>12. Contato</h2><p>Dúvidas, suporte e solicitações: <a href="mailto:onkashfinance@gmail.com">onkashfinance@gmail.com</a>.</p></section>
  </PaginaLegal>;
}
