"use client";
import { useEffect, useState } from "react";
import { AreaAutenticada } from "@/componentes/AreaAutenticada";
import { Badge, Campo, Modal } from "@/componentes/Base";
import { ConfirmacaoAcao, MenuAcoes } from "@/componentes/MenuAcoes";
import { useAutenticacao } from "@/contextos/AutenticacaoContexto";
import { requisicao } from "@/servicos/api";
import type { Categoria, Conta, LancamentoPessoal } from "@/tipos/api";
import { data, moeda, textoEnum } from "@/utilitarios/formatadores";

export function LancamentosPessoaisFuncionais() {
 const {sessao}=useAutenticacao(); const [itens,setItens]=useState<LancamentoPessoal[]>([]),[contas,setContas]=useState<Conta[]>([]),[cats,setCats]=useState<Categoria[]>([]),[editando,setEditando]=useState<LancamentoPessoal|null>(null),[cancelando,setCancelando]=useState<LancamentoPessoal|null>(null),[erro,setErro]=useState(""),[sucesso,setSucesso]=useState(""),[salvando,setSalvando]=useState(false);
 const carregar=async()=>{if(!sessao)return;try{const[l,c,categorias]=await Promise.all([requisicao<LancamentoPessoal[]>("/api/pessoal/lancamentos",{},sessao.token),requisicao<Conta[]>("/api/pessoal/contas",{},sessao.token),requisicao<Categoria[]>("/api/pessoal/categorias",{},sessao.token)]);setItens(l);setContas(c);setCats(categorias)}catch{setErro("Não foi possível carregar os lançamentos.")}};
 useEffect(()=>{void carregar()},[sessao]);
 const editar=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!sessao||!editando)return;const f=new FormData(e.currentTarget),novo=editando.id==="novo";setSalvando(true);try{await requisicao(novo?"/api/pessoal/lancamentos":`/api/pessoal/lancamentos/${editando.id}`,{method:novo?"POST":"PUT",body:JSON.stringify({contaId:f.get("contaId"),categoriaId:f.get("categoriaId")||null,tipo:f.get("tipo"),descricao:f.get("descricao"),valor:Number(f.get("valor")),data:f.get("data"),observacao:f.get("observacao")||null})},sessao.token);setEditando(null);setSucesso(novo?"Lançamento cadastrado com sucesso.":"Alterações salvas com sucesso.");await carregar()}catch{setErro("Não foi possível salvar as alterações.")}finally{setSalvando(false)}};
 const cancelar=async()=>{if(!sessao||!cancelando)return;try{await requisicao(`/api/pessoal/lancamentos/${cancelando.id}`,{method:"DELETE"},sessao.token);setCancelando(null);setSucesso("Lançamento cancelado com sucesso.");await carregar()}catch{setErro("Não foi possível cancelar o lançamento.")}};
 return <AreaAutenticada tipo="pessoal"><header className="cabecalho"><div><h1>Lançamentos</h1><p>Consulte suas entradas e saídas.</p></div><button className="botao" onClick={()=>setEditando({id:"novo",contaId:"",conta:"",tipo:"ENTRADA",descricao:"",valor:0,data:"",cancelado:false})}>+ Novo lançamento</button></header>{sucesso&&<p className="mensagem sucesso">{sucesso}</p>}{erro?<p className="mensagem erro">{erro}</p>:<div className="tabela"><table><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th>Conta</th><th>Valor</th><th>Status</th><th aria-label="Mais opções"/></tr></thead><tbody>{itens.map(i=><tr key={i.id}><td data-label="Data">{data(i.data)}</td><td data-label="Descrição">{i.descricao}</td><td data-label="Tipo">{textoEnum(i.tipo)}</td><td data-label="Conta">{i.conta}</td><td data-label="Valor">{moeda(i.valor)}</td><td data-label="Status"><Badge valor={i.cancelado?"CANCELADO":"Ativo"}/></td><td data-label="Mais opções">{!i.cancelado&&<MenuAcoes acoes={[{rotulo:"Editar",executar:()=>setEditando(i)},{rotulo:"Cancelar",perigosa:true,executar:()=>setCancelando(i)}]}/>}</td></tr>)}</tbody></table></div>}{editando&&<Modal titulo={editando.id==="novo"?"Novo lançamento":"Editar lançamento"} fechar={()=>setEditando(null)}><form className="formulario" onSubmit={editar}><label className="campo">Conta<select name="contaId" defaultValue={editando.contaId} required><option value="">Selecione</option>{contas.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label className="campo">Categoria<select name="categoriaId" defaultValue={editando.categoriaId??""}><option value="">Não informado</option>{cats.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label className="campo">Tipo<select name="tipo" defaultValue={editando.tipo}><option value="ENTRADA">Entrada</option><option value="SAIDA">Saída</option></select></label><Campo label="Descrição" name="descricao" defaultValue={editando.descricao} required/><Campo label="Valor" name="valor" type="number" min="0.01" step="0.01" defaultValue={editando.valor||""} required/><Campo label="Data" name="data" type="date" defaultValue={editando.data} required/><Campo label="Observação" name="observacao" defaultValue={editando.observacao??""}/><button className="botao" disabled={salvando}>{salvando?"Salvando...":editando.id==="novo"?"Salvar lançamento":"Salvar alterações"}</button></form></Modal>}{cancelando&&<Modal titulo="Cancelar lançamento" fechar={()=>setCancelando(null)}><ConfirmacaoAcao descricao="Esta ação preservará o histórico financeiro." textoConfirmar="Confirmar cancelamento" confirmar={()=>void cancelar()} fechar={()=>setCancelando(null)}/></Modal>}</AreaAutenticada>;
}
