import { PaginaLegal } from "@/componentes/PaginaLegal";

export default function PoliticaPrivacidade() {
  return <PaginaLegal titulo="Política de Privacidade" subtitulo="Saiba quais dados são tratados, para quais finalidades e como exercer seus direitos.">
    <section><h2>1. Quem controla seus dados</h2><p>O controlador é <strong>Pedro Henrique Benvento</strong>, responsável pela plataforma <strong>OnKash Finance</strong>, localizado em Curitiba/PR. Dúvidas e solicitações sobre dados pessoais podem ser enviadas para <a href="mailto:onkashfinance@gmail.com">onkashfinance@gmail.com</a>.</p></section>
    <section><h2>2. A quem esta política se aplica</h2><p>Esta política se aplica aos usuários das áreas pessoal e empresarial do OnKash Finance. A plataforma é destinada a pessoas com 18 anos ou mais e não coleta intencionalmente dados de crianças ou adolescentes.</p></section>
    <section><h2>3. Dados tratados</h2><ul><li><strong>Cadastro:</strong> nome, e-mail, senha protegida por hash, tipo de conta, empresa e perfil.</li><li><strong>Dados financeiros:</strong> contas, categorias, saldos, lançamentos, cartões, faturas, orçamentos, recorrências, clientes, fornecedores, contas a pagar e receber.</li><li><strong>Arquivos:</strong> comprovantes enviados voluntariamente pelo usuário.</li><li><strong>Segurança e uso:</strong> endereço IP, agente do navegador, horários, aceite das políticas, operações realizadas e dados técnicos da sessão.</li><li><strong>Comunicação:</strong> e-mail e códigos necessários à verificação da conta.</li></ul></section>
    <section><h2>4. Finalidades e bases legais</h2><p>Os dados são utilizados para criar e manter a conta, executar as funções financeiras solicitadas, autenticar o usuário, prevenir fraude, prestar suporte, cumprir obrigações legais e proteger direitos. Conforme o caso, o tratamento se fundamenta na execução de contrato ou de procedimentos preliminares, cumprimento de obrigação legal ou regulatória, exercício regular de direitos, legítimo interesse após avaliação de necessidade e, quando exigido, consentimento.</p><p>Dados obrigatórios para executar o serviço são identificados no momento da coleta. O aceite dos Termos registra ciência das condições; consentimentos opcionais, se introduzidos futuramente, serão apresentados separadamente e poderão ser revogados.</p></section>
    <section><h2>5. Compartilhamento e operadores</h2><p>Os dados são compartilhados apenas quando necessário para operar o serviço:</p><ul><li><strong>Render:</strong> hospedagem da interface, API e infraestrutura de banco de dados.</li><li><strong>Brevo:</strong> envio de e-mails transacionais, como códigos de verificação.</li><li><strong>Autoridades e assessores:</strong> quando exigido por lei, decisão válida ou para exercício de direitos.</li></ul><p>Não vendemos dados pessoais. Como fornecedores podem utilizar infraestrutura fora do Brasil, poderá ocorrer transferência internacional com as salvaguardas contratuais e legais aplicáveis. A lista será atualizada quando novos operadores relevantes forem contratados.</p></section>
    <section><h2>6. Armazenamento e retenção</h2><p>Dados da conta são mantidos enquanto ela estiver ativa e pelo período necessário para atender às finalidades informadas, obrigações legais, prevenção de fraude e exercício de direitos. Solicitações de exclusão são analisadas para eliminar ou anonimizar o que não precisar ser conservado. Registros técnicos de operações são mantidos por até 180 dias; códigos de verificação expirados são descartados pela rotina de retenção. Aceites e protocolos podem ser preservados pelo prazo necessário à comprovação de obrigações e ao exercício de direitos. Backups seguem o ciclo seguro do fornecedor e podem levar tempo adicional para expiração.</p></section>
    <section><h2>7. Segurança</h2><p>São adotadas medidas como HTTPS, hash de senhas, verificação de e-mail, autenticação por token com expiração, separação por usuário ou empresa, permissões, limites de tentativas, validação de arquivos, cabeçalhos de segurança, registro de operações e armazenamento de segredos fora do código. Nenhum sistema é absolutamente invulnerável; incidentes serão investigados e comunicados quando houver risco ou dano relevante, conforme a legislação.</p></section>
    <section><h2>8. Seus direitos</h2><p>Você pode solicitar confirmação e acesso, correção, informações sobre compartilhamento, portabilidade, anonimização, bloqueio ou eliminação de dados desnecessários ou irregulares, oposição, revisão de decisões automatizadas e revogação de consentimento quando aplicável. Após entrar, acesse <strong>Privacidade e dados</strong> para exportar informações ou gerar um protocolo. Também é possível escrever para o canal informado acima.</p></section>
    <section><h2>9. Cookies e armazenamento local</h2><p>O OnKash utiliza apenas mecanismos essenciais para sessão e preferências, como armazenamento local do token e do tema. Não utilizamos cookies publicitários nesta versão. Se ferramentas opcionais de marketing ou análise forem adicionadas, esta política e os controles de escolha serão atualizados antes da ativação.</p></section>
    <section><h2>10. Atualizações</h2><p>Mudanças relevantes serão informadas na plataforma. Uma nova versão poderá exigir ciência ou novo aceite. O histórico de aceites é mantido para demonstrar qual documento foi apresentado ao usuário.</p></section>
    <section><h2>11. Contato</h2><p>Controlador: Pedro Henrique Benvento · OnKash Finance · Curitiba/PR<br/>Canal de privacidade: <a href="mailto:onkashfinance@gmail.com">onkashfinance@gmail.com</a></p></section>
  </PaginaLegal>;
}
